In [1]:
import numpy as np

Creating arrays from python lists:

In [2]:
np.array([2,3,7,8])

array([2, 3, 7, 8])

In [3]:
np.array([3.2,5,6,1,4.5])

array([3.2, 5. , 6. , 1. , 4.5])

In [4]:
np.array([4.5,7,6.5,7.0],dtype=int)

array([4, 7, 6, 7])

In [7]:
#nested list results multidimension array
np.array([range(i,i+2)for i in [5,6,8]])


array([[5, 6],
       [6, 7],
       [8, 9]])

Creating arrays from scratch

In [8]:
#create a length-20 arrray filled with zeroes
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#create a 3*4 array all filled with 1
np.full((3,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
#create a sequence in modifed way
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [15]:
#create an array of evenly spaced 
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
#create array of uniformly distributed 3*3 with the random in between 0,1
np.random.random((3,3))

array([[0.9741536 , 0.11629001, 0.27938821],
       [0.71316014, 0.83797335, 0.58374258],
       [0.60664582, 0.9761381 , 0.41335537]])

In [20]:
#create array of 3*3 random distributed with mean 1, std dev 5
np.random.normal(1,5,(3,3))

array([[ -2.88752506,   8.63028874,  -1.74372347],
       [  8.23488656,  -6.89545639,   8.44214327],
       [-13.65401636,   2.45887861,   2.21357355]])

In [21]:
#create array of random of 3*3 between 0,10 integer
np.random.randint(0,10,(3,3))

array([[3, 7, 0],
       [2, 5, 1],
       [7, 6, 4]])

In [22]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numpy  Array Attributes
ndim(no. of dimensions)
shape(size of each dimension)
size(total size of array)

In [30]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4)) #2dim array
x3=np.random.randint(10,size=(3,4,5)) #3dim array

In [31]:
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [32]:
np.random.randint(10,size=(3,4))

array([[2, 8, 0, 2],
       [9, 2, 8, 1],
       [3, 6, 7, 7]])

### Array Indexing: Accessing single elements

In [33]:
x1

array([5, 2, 4, 8, 2, 9])

In [34]:
x1[0]

5

In [35]:
x2

array([[5, 8, 9, 2],
       [2, 2, 9, 0],
       [1, 1, 2, 0]])

In [36]:
x2[1,0]

2

In [38]:
x2[1,-1]

0

In [40]:
x1[0]=3.14
x1

array([3, 2, 4, 8, 2, 9])

### Array Slicing: Acessing subarray

x[start:stop:step] default- start=0,stop=size of dim, step=1

In [47]:
x=np.arange(10)
x
# 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x[:5]

array([0, 1, 2, 3, 4])

In [44]:
x[1:8:2]

array([1, 3, 5, 7])

In [45]:
x[::2]

array([0, 2, 4, 6, 8])

In [46]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
x2
#2D array

array([[5, 8, 9, 2],
       [2, 2, 9, 0],
       [1, 1, 2, 0]])

In [50]:
x2[:2,:3]

array([[5, 8, 9],
       [2, 2, 9]])

In [51]:
x2[:3,::2]

array([[5, 9],
       [2, 9],
       [1, 2]])

In [52]:
x2[::-1,::-1]

array([[0, 2, 1, 1],
       [0, 9, 2, 2],
       [2, 9, 8, 5]])

In [53]:
x2[:1]

array([[5, 8, 9, 2]])

In [56]:
x2[:,0]

array([5, 2, 1])

In [57]:
x2[0]

array([5, 8, 9, 2])

Interesting feature!!! (Subarray as no copy views)

In [59]:
#slicing of array return only view not copy as in the python list
x2

array([[5, 8, 9, 2],
       [2, 2, 9, 0],
       [1, 1, 2, 0]])

In [61]:
#extract the subarray
x2_sub=x2[:2,:2]
x2_sub

array([[5, 8],
       [2, 2]])

In [62]:
x2_sub[0,0]=10
x2_sub

array([[10,  8],
       [ 2,  2]])

In [64]:
x2    
#it is quite useful for large datast manupulation(as we hae handle small set)

array([[10,  8,  9,  2],
       [ 2,  2,  9,  0],
       [ 1,  1,  2,  0]])

But for creating copies of arrays using method copy()

In [65]:
x2_sub_copy=x2[:2,:2].copy()
x2_sub_copy

array([[10,  8],
       [ 2,  2]])

In [66]:
x2_sub_copy[0,0]=14
x2_sub_copy

array([[14,  8],
       [ 2,  2]])

In [67]:
x2

array([[10,  8,  9,  2],
       [ 2,  2,  9,  0],
       [ 1,  1,  2,  0]])

### Reshaping of Arrays

In [68]:
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
x=np.array([1,5,2,6])
x

array([1, 5, 2, 6])

In [72]:
x.reshape((1,4))

array([[1, 5, 2, 6]])

In [73]:
x[np.newaxis,:]

array([[1, 5, 2, 6]])

In [75]:
x.reshape((4,1))

array([[1],
       [5],
       [2],
       [6]])

### Array Concatenate and Splitting

In [5]:
#concatenation is done using the np.concatenate, np.vstack,np.hsatck
x=np.array([1,4,5,3])
y=np.array([2,3,4,5])
con=np.concatenate([x,y])
con


array([1, 4, 5, 3, 2, 3, 4, 5])

In [8]:
con1=np.array([[20,10],
               [12,34]])
np.concatenate([con1,con1])

array([[20, 10],
       [12, 34],
       [20, 10],
       [12, 34]])

In [9]:
a=np.array([7,8])
np.vstack([a,con1])

array([[ 7,  8],
       [20, 10],
       [12, 34]])

In [13]:
b=np.array([[2],
            [3]])
np.hstack([b,con1])

array([[ 2, 20, 10],
       [ 3, 12, 34]])

In [15]:
#split is oppeste to the concatenate
x=np.array([1,2,4,5,6,8,7])
x1,x2,x3=np.split(x,[3,6])
print(x1,x2,x3)

[1 2 4] [5 6 8] [7]


### Computation on Numpy Arrays: Universal Functions(UFuncs)

In [4]:
# computaion on numpy array can be made fast using vectorized operation wchich is implemented using ufuncs
# implementaion using ufuncs take less time as compared to the loop operation
x= np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
x=np.arange(4)
#arithmetic operation
print("x =",x)
print("x+3=",x+3)
print("x*2=",x*2)

x = [0 1 2 3]
x+3= [3 4 5 6]
x*2= [0 2 4 6]


In [7]:
#trigonometric operation
theta= np.linspace(0,np.pi,3)
print("theta =",theta)
print("sin(theta)=",np.sin(theta))


theta = [0.         1.57079633 3.14159265]
sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [8]:
#advanced ufuncs
#(Specifying output)
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
y


array([ 0., 10., 20., 30., 40.])

### Aggregations: Min, Max and many more

In [10]:
# Summing the values of the array
l=np.random.random(1000)
%timeit sum(l)
%timeit np.sum(l)

251 µs ± 3.15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
8.95 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
min(l),max(l)

(0.0005153347553044085, 0.9979173984400137)

In [12]:
np.min(l),np.max(l)

(0.0005153347553044085, 0.9979173984400137)

In [13]:
%timeit min(l)
%timeit np.min(l)

156 µs ± 1.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
8.8 µs ± 261 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
#multidimensional aggregates
m=np.random.random((3,4))
m

array([[0.20542995, 0.44220936, 0.745219  , 0.74834312],
       [0.40405485, 0.5664284 , 0.95281568, 0.62893824],
       [0.23990195, 0.87538715, 0.52856562, 0.86607608]])

In [15]:
m.sum()

7.203369412607092

In [17]:
m.min(axis=0) # each column specify axis=0

array([0.20542995, 0.44220936, 0.52856562, 0.62893824])

In [18]:
m.max(axis=1)

array([0.74834312, 0.95281568, 0.87538715])

### Computation on Arrays : Broadcasting

In [3]:
# add scalar to array
a=np.arange(4)
a

array([0, 1, 2, 3])

In [4]:
a+3

array([3, 4, 5, 6])

In [5]:
# add 1D array to 2D array
m=np.ones((4,4))
m

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
a+m

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [12]:
# another example
q=np.arange(3)
u=np.arange(3)[:,np.newaxis]
q


array([0, 1, 2])

In [13]:
u

array([[0],
       [1],
       [2]])

In [14]:
q+u

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Comprasions ,Boolean Logic :

In [16]:
x=np.array([2,5,3,7,4,8,1,0])
x<4

array([ True, False,  True, False, False, False,  True,  True])

In [17]:
x==3

array([False, False,  True, False, False, False, False, False])

In [18]:
a=np.random.randint(10,size=(3,4))
a

array([[5, 4, 5, 0],
       [6, 4, 9, 7],
       [8, 0, 2, 0]])

In [19]:
#how many values less than 5?
np.count_nonzero(a<5)

6

In [21]:
# how many values less than 5 in each row?
np.sum(a<5,axis=1)

array([2, 1, 3])

In [23]:
# are there any values less than 7
np.any(a<7)

True

### Fancy Indexing

In [3]:
#fancy indexing means to access multiple array elements at once
x=np.random.randint(100,size=15)
x

array([68, 66, 59, 53, 96,  6, 78, 64, 41, 58, 40, 26, 62, 76, 97])

In [6]:
index=[3,5,2]
x[index]

array([53,  6, 59])

In [11]:
# combined Indexing
x=np.random.randint(100,size=(3,4))
x

array([[69, 44, 51, 75],
       [54, 64, 96, 43],
       [80, 76, 68, 49]])

In [13]:
x[2,[2,1,0]]


array([68, 76, 80])

In [15]:
x[1:,[0,3,1]]

array([[54, 43, 64],
       [80, 49, 76]])

In [17]:
#fancy indexing can be used to modify array data
x=np.arange(10)
i=np.array([2,3,6,4,8,5,1])
x[i]=44
x

array([ 0, 44, 44, 44, 44, 44, 44,  7, 44,  9])

### Sorting:

In [20]:
# default sorting alorithm used is Quicksort with complexity O(N*logN)
x=np.array([5,2,6,1,9,4,3,2,6,0,3])
np.sort(x)

array([0, 1, 2, 2, 3, 3, 4, 5, 6, 6, 9])

In [21]:
# argsort(return the indices of sorted elements)
x

array([5, 2, 6, 1, 9, 4, 3, 2, 6, 0, 3])

In [22]:
i=np.argsort(x)
i

array([ 9,  3,  1,  7,  6, 10,  5,  0,  2,  8,  4], dtype=int64)

In [24]:
#Sorting Along Row and columns
x=np.random.randint(100,size=(5,7))
x

array([[25, 16,  2, 57,  2, 16,  8],
       [55, 40, 58, 62, 72, 68, 20],
       [ 0,  2, 98, 85, 43, 99, 28],
       [58, 54, 35, 72,  9, 32, 38],
       [62,  5, 43, 21, 44, 24, 10]])

In [25]:
# Sorting along Columns
np.sort(x,axis=0)

array([[ 0,  2,  2, 21,  2, 16,  8],
       [25,  5, 35, 57,  9, 24, 10],
       [55, 16, 43, 62, 43, 32, 20],
       [58, 40, 58, 72, 44, 68, 28],
       [62, 54, 98, 85, 72, 99, 38]])

In [26]:
# Sorting along Row
np.sort(x,axis=1)

array([[ 2,  2,  8, 16, 16, 25, 57],
       [20, 40, 55, 58, 62, 68, 72],
       [ 0,  2, 28, 43, 85, 98, 99],
       [ 9, 32, 35, 38, 54, 58, 72],
       [ 5, 10, 21, 24, 43, 44, 62]])

In [27]:
# partial Sorts : Partitioning
a=np.array([2,5,7,9,2,6,1])
np.partition(a,4)

array([2, 1, 2, 5, 6, 7, 9])

In [28]:
x

array([[25, 16,  2, 57,  2, 16,  8],
       [55, 40, 58, 62, 72, 68, 20],
       [ 0,  2, 98, 85, 43, 99, 28],
       [58, 54, 35, 72,  9, 32, 38],
       [62,  5, 43, 21, 44, 24, 10]])

In [32]:
np.partition(x,2,axis=1)

array([[ 2,  2,  8, 57, 16, 16, 25],
       [20, 40, 55, 62, 72, 68, 58],
       [ 0,  2, 28, 85, 43, 99, 98],
       [ 9, 32, 35, 72, 58, 54, 38],
       [ 5, 10, 21, 43, 44, 24, 62]])