# Data Manupulation with Pandas

#### lets introduce 3 fandamental Pandas DataFrame
 1.Series, 2.DataFrame and 3.Index

In [1]:
import numpy as np
import pandas as pd

### 1. Series

In [22]:
data=pd.Series([2,4,6,1,8,0])
data
# Series format pd.Series(data,index=index)

0    2
1    4
2    6
3    1
4    8
5    0
dtype: int64

In [3]:
data.values   # act as array

array([2, 4, 6, 1, 8, 0], dtype=int64)

In [7]:
data[3] # access single value

1

In [8]:
data[1:4] # access multiple values

1    4
2    6
3    1
dtype: int64

In [12]:
# Series can be explicitly defined index
# Series as generalized Numpy array
data= pd.Series([2,4,6],index=['a','b','c'])
data
                

a    2
b    4
c    6
dtype: int64

In [13]:
data['a'] # access

2

In [16]:
# Series is the Specialized dictionary
# population of city in Millions
pop_dict= {'California':38,
           'Texas':26,
           'New York':19,
           'Florida':19
          }
pop_dict

{'California': 38, 'Florida': 19, 'New York': 19, 'Texas': 26}

In [17]:
population=pd.Series(pop_dict)
population

California    38
Florida       19
New York      19
Texas         26
dtype: int64

In [21]:
# slicing is possible now unlike dictionary
population['Texas':'Florida']

Series([], dtype: int64)

### 2. DataFrame

In [29]:
# Dataframe as a generalised Numpy array 2D array with row and columns
area_dict={'California':42,
           'Texas':69,
           'New York':14,
           'Florida':17}
area=pd.Series(area_dict)
area

California    42
Florida       17
New York      14
Texas         69
dtype: int64

In [30]:
states= pd.DataFrame({'population':population,
                      'area':area})
states

area  population
California    42          38
Florida       17          19
New York      14          19
Texas         69          26

In [31]:
states.index

Index(['California', 'Florida', 'New York', 'Texas'], dtype='object')

In [32]:
states.columns

Index(['area', 'population'], dtype='object')

In [34]:
states['area'] #access columns

California    42
Florida       17
New York      14
Texas         69
Name: area, dtype: int64

#### Constructing DataFrame objects

In [35]:
#From a single Series object
pd.DataFrame(population,columns=['population'])

population
California          38
Florida             19
New York            19
Texas               26

In [38]:
#From a list of dicts
data=[{'a':i,'b':2*i}
for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [39]:
#From a dictionary of Series objects
pd.DataFrame({'population':population,
              'area':area})

area  population
California    42          38
Florida       17          19
New York      14          19
Texas         69          26

In [41]:
#From a 2D Numpy array
pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo','alex'],
             index=['a','b','c'])

foo  alex
a    8     1
b    5     0
c    1     0

### 3.Index

In [43]:
# Index object can be thought of either immutable array or as an ordered set
ind=pd.Index([3,5,2,1,9,5])
ind

Int64Index([3, 5, 2, 1, 9, 5], dtype='int64')

In [44]:
ind[3]

1

In [45]:
ind[::2]

Int64Index([3, 2, 9], dtype='int64')

In [46]:
# cannot modified via normal means
ind[2]=7

TypeError: Index does not support mutable operations

In [48]:
# Index as Ordered set
indA=pd.Index([3,4,6,8,9,1])
indB=pd.Index([3,4,5,7,9,3])


In [49]:
indA&indB   # intersection

Int64Index([3, 3, 4, 9], dtype='int64')

In [50]:
indA|indB   # union

Int64Index([1, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

## Data Indexing and Selection

#### Data Selection in Series

In [2]:
# Series as dictionary
data=pd.Series([3,4,2],index=['a','b','c'])
data

a    3
b    4
c    2
dtype: int64

In [3]:
data['a']

3

In [4]:
'a' in data

True

In [7]:
data['b']=2   # easily mutable
data

a    3
b    2
c    2
dtype: int64

In [8]:
# Series as 1D array
# Slicing by explicit index
data['a':'b']

a    3
b    2
dtype: int64

In [9]:
#Slicing implicit index
data[:2]

a    3
b    2
dtype: int64

In [14]:
#masking
data[(data<3)]

b    2
c    2
dtype: int64

In [15]:
# Indexers: loc ,iloc
data=pd.Series(['a','b','c','d'], index=[1,3,5,6])
data

1    a
3    b
5    c
6    d
dtype: object

In [17]:
# Confusion for the numerical index, pandas provide indexiers attributes
data.loc[1]   # explicit index

'a'

In [18]:
data.loc[1:4]

1    a
3    b
dtype: object

In [19]:
data[1:4]   

3    b
5    c
6    d
dtype: object

In [22]:
data.iloc[1]   # python implict style index

'b'

In [21]:
data.iloc[1:4]

3    b
5    c
6    d
dtype: object

#### Data Selection in DataFrame

In [23]:
# DataFrame as a dictionary
area=pd.Series({'California':42,
           'Texas':69,
           'New York':14,
           'Florida':17})
pop=pd.Series({'California':38,
           'Texas':26,
           'New York':19,
           'Florida':19
          })
data=pd.DataFrame({'area':area,'pop':pop})
data

area  pop
California    42   38
Florida       17   19
New York      14   19
Texas         69   26

In [24]:
data['area']

California    42
Florida       17
New York      14
Texas         69
Name: area, dtype: int64

In [25]:
data.area

California    42
Florida       17
New York      14
Texas         69
Name: area, dtype: int64

In [26]:
data.area is data['area']

True

In [27]:
# But sometime the above statement is not true, if the columns names are not srtings, or if the column names 
# conflict with methods of DataFrame

In [28]:
data.pop is data['pop']

False

In [29]:
# SO avoid using data.pop=z

In [30]:
data['density']=data['pop']/data['area']
data

area  pop   density
California    42   38  0.904762
Florida       17   19  1.117647
New York      14   19  1.357143
Texas         69   26  0.376812

In [31]:
# DataFrame as 2D array
data.values

array([[42.        , 38.        ,  0.9047619 ],
       [17.        , 19.        ,  1.11764706],
       [14.        , 19.        ,  1.35714286],
       [69.        , 26.        ,  0.37681159]])

In [32]:
data.T  # transpose

California    Florida   New York      Texas
area      42.000000  17.000000  14.000000  69.000000
pop       38.000000  19.000000  19.000000  26.000000
density    0.904762   1.117647   1.357143   0.376812

In [34]:
data.values[0]  # access the single row

array([42.       , 38.       ,  0.9047619])

In [35]:
data.iloc[:2,:3]

area  pop   density
California    42   38  0.904762
Florida       17   19  1.117647

In [36]:
data.loc['Florida':'Texas']

area  pop   density
Florida     17   19  1.117647
New York    14   19  1.357143
Texas       69   26  0.376812

In [37]:
data.loc[data.density>1,['pop','area']]

pop  area
Florida    19    17
New York   19    14

## Operating on Data in Pandas

In [39]:
df=pd.DataFrame(np.random.randint(0,10,(3,4)), columns=['A','B','C','D'])
df

A  B  C  D
0  8  8  4  6
1  3  7  2  7
2  7  5  8  6

In [40]:
np.exp(df)

A            B            C            D
0  2980.957987  2980.957987    54.598150   403.428793
1    20.085537  1096.633158     7.389056  1096.633158
2  1096.633158   148.413159  2980.957987   403.428793

In [41]:
np.sin(df*np.pi/4)

A             B             C         D
0 -2.449294e-16 -2.449294e-16  1.224647e-16 -1.000000
1  7.071068e-01 -7.071068e-01  1.000000e+00 -0.707107
2 -7.071068e-01 -7.071068e-01 -2.449294e-16 -1.000000

In [44]:
# Index alignment in Series
a=pd.Series([2,4,5,6],index=[1,2,0,3])
b=pd.Series([2,3,7,8], index=[2,4,1,0])
a+b

0    13.0
1     9.0
2     6.0
3     NaN
4     NaN
dtype: float64

In [46]:
a.add(b,fill_value=0)

0    13.0
1     9.0
2     6.0
3     6.0
4     3.0
dtype: float64

In [47]:
# index alignment in DataFrame
a=pd.DataFrame(np.random.randint(0,10,(3,5)),columns=list('ABCDE'))
a

A  B  C  D  E
0  0  3  5  6  7
1  6  6  2  7  7
2  6  9  9  0  2

In [49]:
b=pd.DataFrame(np.random.randint(0,10,(3,3)),columns=list('ABC'))
b

A  B  C
0  8  4  3
1  8  7  9
2  3  0  4

In [50]:
a+b

A   B   C   D   E
0   8   7   8 NaN NaN
1  14  13  11 NaN NaN
2   9   9  13 NaN NaN

In [51]:
fill=a.stack().mean()
a.add(b,fill_value=fill)

A   B   C     D     E
0   8   7   8  11.0  12.0
1  14  13  11  12.0  12.0
2   9   9  13   5.0   7.0

## Handling Missing Data

In [52]:
# Missing data is very common in real worl dataset


In [53]:
# None: Pythonic missing data
val=np.array([1,2,3,None])
val

array([1, 2, 3, None], dtype=object)

In [63]:
# since data type of None is object it takes more time and does not perform binary operation
val.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [55]:
# NaN : Miissing numerical data
val1=np.array([2,3,5,np.nan])
val1

array([ 2.,  3.,  5., nan])

In [57]:
1+np.nan  # it does not show error

nan

In [59]:
# but it not always useful
val1.sum()

nan

In [61]:
# Numpy does some aggregation to ignore missing values
np.nansum(val1)

10.0

In [64]:
# nan and none are nearly interchangable
pd.Series([2,4,7,None])

0    2.0
1    4.0
2    7.0
3    NaN
dtype: float64

#### Operating on Null values

In [91]:
# Detecting null values

In [87]:
data=pd.Series([2,'hello',None,np.nan])
data.isnull()

0    False
1    False
2     True
3     True
dtype: bool

In [89]:
# Dropping null values

In [90]:
data.dropna()

0        2
1    hello
dtype: object

In [72]:
df=pd.DataFrame([[1,3,np.nan],
                [3,5,8],
                [4,np.nan,2]])
df

0    1    2
0  1  3.0  NaN
1  3  5.0  8.0
2  4  NaN  2.0

In [73]:
df.dropna()  # drop all null values

0    1    2
1  3  5.0  8.0

In [76]:
df.dropna(axis=1) # drop all columns contain null values

0
0  1
1  3
2  4

In [79]:
df[3]=np.nan
df

0    1    2   3
0  1  3.0  NaN NaN
1  3  5.0  8.0 NaN
2  4  NaN  2.0 NaN

In [84]:
# But the above drop has disadvantage of dropping some good data
# So we use the how or thresh parameter to control
df.dropna(axis=1,how='all')
#how='any'

0    1    2
0  1  3.0  NaN
1  3  5.0  8.0
2  4  NaN  2.0

In [86]:
df.dropna(axis='columns',thresh=2)
# thresh parameter lets you specify a minimum number of non null values for row/columns to be kept

0    1    2
0  1  3.0  NaN
1  3  5.0  8.0
2  4  NaN  2.0

In [88]:
# Filling null values

In [93]:
data=pd.Series([1,np.nan,3,np.nan,4], index=list('abcde'))
data

a    1.0
b    NaN
c    3.0
d    NaN
e    4.0
dtype: float64

In [94]:
data.fillna(0)

a    1.0
b    0.0
c    3.0
d    0.0
e    4.0
dtype: float64

In [95]:
# forward fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    3.0
d    3.0
e    4.0
dtype: float64

In [96]:
#backward fill
data.fillna(method='bfill')

a    1.0
b    3.0
c    3.0
d    4.0
e    4.0
dtype: float64

In [97]:
df

0    1    2   3
0  1  3.0  NaN NaN
1  3  5.0  8.0 NaN
2  4  NaN  2.0 NaN

In [103]:
df.fillna(method='ffill',axis='columns')

0    1    2    3
0  1.0  3.0  3.0  3.0
1  3.0  5.0  8.0  8.0
2  4.0  4.0  2.0  2.0

## Hierarchical Indexing

In [104]:
# Pandas MultiIndex (to handle the higher dimension of data)

In [3]:
index=[('California',2000),('California',2010),('New York',2000),('New York',2010),('Texas',2000),('Texas',2010)]
population=[33,37,18,19,20,25]
pop=pd.Series(population,index=index)

In [4]:
index=pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [5]:
pop=pop.reindex(index)
pop

California  2000    33
            2010    37
New York    2000    18
            2010    19
Texas       2000    20
            2010    25
dtype: int64

In [6]:
pop[:,2010]

California    37
New York      19
Texas         25
dtype: int64

In [8]:
pop_df=pop.unstack() # unstack() method quickly convert the indexed Series to indexed  DataFrame
pop_df

2000  2010
California    33    37
New York      18    19
Texas         20    25

In [9]:
pop_df.stack() # do it opposite

California  2000    33
            2010    37
New York    2000    18
            2010    19
Texas       2000    20
            2010    25
dtype: int64

## Combining Datasets : concat and append

In [2]:
# pd.concat(objs,axis=0, join='outer',join_aexs=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, copy=True)

In [6]:
def make_df(cols,ind):
    data={c: [str(c)+str(i) for i in ind]
         for c in cols}
    return pd.DataFrame(data,ind)
make_df('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [9]:
df1=make_df('AB',[1,2])
df2=make_df('AB',[3,4])
print(df1)
print(df2)

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4


In [10]:
print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [11]:
df3=make_df('AB',[1,2])
df4=make_df('CD',[1,2])
print(df3)
print(df4)

    A   B
1  A1  B1
2  A2  B2
    C   D
1  C1  D1
2  C2  D2


In [15]:
pd.concat([df3,df4],axis='columns') # concatenate on column wise

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [16]:
# duplicate index
x=make_df('AB',[0,1])
y=make_df('AB',[2,3])
y.index=x.index        # make duplicate indices
print(x)
print(y)

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3


In [17]:
pd.concat([x,y])

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [18]:
# catching the repeats as an error
try:
    pd.concat([x,y],verify_integrity=True)
except ValueError as e :
    print("ValueError:",e)

ValueError: Indexes have overlapping values: [0, 1]


In [19]:
# ignoring the index
pd.concat([x,y],ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [20]:
# adding the multiindex keys
pd.concat([x,y],keys=['x','y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [21]:
# concatenation with joins
df5=make_df('ABC',[3,4])
df6=make_df('BCD',[5,6])
pd.concat([df5,df6])

A   B   C    D
3   A3  B3  C3  NaN
4   A4  B4  C4  NaN
5  NaN  B5  C5   D5
6  NaN  B6  C6   D6

In [23]:
pd.concat([df5,df6],join='inner')  # intersection of columns

B   C
3  B3  C3
4  B4  C4
5  B5  C5
6  B6  C6

In [25]:
pd.concat([df5,df6],join_axes=[df5.columns])

A   B   C
3   A3  B3  C3
4   A4  B4  C4
5  NaN  B5  C5
6  NaN  B6  C6

In [28]:
# append() method
x.append(y)

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

## Combine Datasets: Merge and Join

In [29]:
# Categories of the joins

In [31]:
# one to one joins
df1=pd.DataFrame({'employee':['Alex','Jhon','Jack','Tom'],
                 'group':['Accounting','Engineering','Engineering','HR']})
df2=pd.DataFrame({'employee':['Jhon','Alex','Jack','Tom'],
                  'hire_date':[2005,2010,2013,2000]})
print(df1)
print(df2)

  employee        group
0     Alex   Accounting
1     Jhon  Engineering
2     Jack  Engineering
3      Tom           HR
  employee  hire_date
0     Jhon       2005
1     Alex       2010
2     Jack       2013
3      Tom       2000


In [33]:
df3=pd.merge(df1,df2)
df3

employee        group  hire_date
0     Alex   Accounting       2010
1     Jhon  Engineering       2005
2     Jack  Engineering       2013
3      Tom           HR       2000

In [34]:
# many to one
df4=pd.DataFrame({'group':['Accounting','Engineering','HR'],
                  'emp_id':[100,101,104]})
df4

emp_id        group
0     100   Accounting
1     101  Engineering
2     104           HR

In [35]:
pd.merge(df3,df4)

employee        group  hire_date  emp_id
0     Alex   Accounting       2010     100
1     Jhon  Engineering       2005     101
2     Jack  Engineering       2013     101
3      Tom           HR       2000     104

In [36]:
# many to many
df5=pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering','HR','HR'],
                 'skill':['math','ml','ai','coding','ds','spreadsheets']})
df5

group         skill
0   Accounting          math
1   Accounting            ml
2  Engineering            ai
3  Engineering        coding
4           HR            ds
5           HR  spreadsheets

In [38]:
pd.merge(df3,df5)

employee        group  hire_date         skill
0     Alex   Accounting       2010          math
1     Alex   Accounting       2010            ml
2     Jhon  Engineering       2005            ai
3     Jhon  Engineering       2005        coding
4     Jack  Engineering       2013            ai
5     Jack  Engineering       2013        coding
6      Tom           HR       2000            ds
7      Tom           HR       2000  spreadsheets

In [39]:
# see 'how' keyword in merge in pandas documentation

In [40]:
# Overlapping columns Names: suffixes keyword
df8=pd.DataFrame({'name':['Alex','Bob','Kevin'],
                  'rank':[1,2,3]})
df9=pd.DataFrame({'name':['Alex','Bob','Kevin'],
                  'rank':[3,6,9]})
print(df8)
print(df9)

    name  rank
0   Alex     1
1    Bob     2
2  Kevin     3
    name  rank
0   Alex     3
1    Bob     6
2  Kevin     9


In [41]:
pd.merge(df8,df9,on='name')

name  rank_x  rank_y
0   Alex       1       3
1    Bob       2       6
2  Kevin       3       9

## Example: US States Data

In [46]:
pop=pd.read_csv('G:\\Download\\data-USstates-master\\state-population.csv')
pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [48]:
areas=pd.read_csv('G:\Download\data-USstates-master\state-areas.csv')
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [49]:
abbreves=pd.read_csv('G:\Download\data-USstates-master\state-abbrevs.csv')
abbreves.head()

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [51]:
# merge the pop and abbreves data
merged=pd.merge(pop,abbreves,how='outer',left_on='state/region',right_on='abbreviation')
merged=merged.drop('abbreviation',1)  # drop the duplicate info
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [54]:
# check for null entries
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [55]:
# some population info is null, lets find out which
merged[merged['population'].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [56]:
# some states are also null
merged.loc[merged['state'].isnull(),'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [57]:
# as we infer that our populatioin data include the entry of Puerto Rico(PR) and United States(USA) so have to fix it
merged.loc[merged['state/region']=='PR','state']='Puerto Rico'
merged.loc[merged['state/region']=='USA','state']='United States'
merged.isnull().any()


state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [58]:
final=pd.merge(merged,areas, on='state',how='left')
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [69]:
final.isnull().any()  # check null 

state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool

In [71]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array([], dtype=object)

In [72]:
final.dropna(inplace=True)
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

## GroupBy : Split, Apply, Combine

1. Split step involves breaking up and grouping a DataFrame depending on the value of the specified key 
2. Apply step involves computing some function,(aggregation,transformation,filtering within the individual gruops
3. Combine step merges the results

In [5]:
df=pd.DataFrame({'key':['A','B','C','A','B','C'],
                 'data':range(6)},columns=['key','data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [6]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [4]:
df=pd.DataFrame({'key':['A','B','C','A','B','C'],
                'data1':range(6),
                'data2':np.random.randint(10,size=6)},
                columns=['key','data1','data2'])
df

key  data1  data2
0   A      0      6
1   B      1      1
2   C      2      7
3   A      3      3
4   B      4      6
5   C      5      7

In [5]:
# Aggregation
df.groupby('key').aggregate([np.min,np.median,np.max])

data1             data2            
     amin median amax  amin median amax
key                                    
A       0    1.5    3     3    4.5    6
B       1    2.5    4     1    3.5    6
C       2    3.5    5     7    7.0    7

In [6]:
df.groupby('key').aggregate({'data1':np.min,
                             'data2':np.max})

data1  data2
key              
A        0      6
B        1      6
C        2      7

In [7]:
# filtering
def filter(x):
    return x['data1'].mean()>2
df.groupby('key').filter(filter)

key  data1  data2
1   B      1      1
2   C      2      7
4   B      4      6
5   C      5      7

In [8]:
# transformation
df.groupby('key').transform(lambda x: x-x.mean())

data1  data2
0   -1.5    1.5
1   -1.5   -2.5
2   -1.5    0.0
3    1.5   -1.5
4    1.5    2.5
5    1.5    0.0

## Working with Time Series

In [9]:
date=pd.to_datetime("14th of September, 2017")
date

Timestamp('2017-09-14 00:00:00')

In [10]:
date.strftime('%A')

'Thursday'

In [11]:
date+pd.to_timedelta(np.arange(10),'D')

DatetimeIndex(['2017-09-14', '2017-09-15', '2017-09-16', '2017-09-17',
               '2017-09-18', '2017-09-19', '2017-09-20', '2017-09-21',
               '2017-09-22', '2017-09-23'],
              dtype='datetime64[ns]', freq=None)

In [12]:
# Indexing by Time
index=pd.DatetimeIndex(['2018-07-11','2018-07-12','2017-09-11','2017-09-12'])
data=pd.Series([1,2,3,4],index=index)
data

2018-07-11    1
2018-07-12    2
2017-09-11    3
2017-09-12    4
dtype: int64

In [13]:
data['2018']

2018-07-11    1
2018-07-12    2
dtype: int64

In [15]:
# Date Range
pd.date_range('2018-06-23', periods=10)

DatetimeIndex(['2018-06-23', '2018-06-24', '2018-06-25', '2018-06-26',
               '2018-06-27', '2018-06-28', '2018-06-29', '2018-06-30',
               '2018-07-01', '2018-07-02'],
              dtype='datetime64[ns]', freq='D')

In [16]:
pd.date_range('2018-06-29', periods=10,freq='M')

DatetimeIndex(['2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30',
               '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31',
               '2019-02-28', '2019-03-31'],
              dtype='datetime64[ns]', freq='M')